### ISSUE TITLE
WT32 SC01 Plus - IDE 2.2.1 borad definition, driver Windows

### ISSUE THREAD

**Issue by Jusufs** [ScitiveX/Smart_touch_switch__weather_station__watch_using_wt32-sc01-plus_esp32s3#1]
Hi,
I received following kit
[https://www.aliexpress.com/item/1005006151445980.html?gps-id=pcStoreNewArrivals&scm=1007.23409.271287.0&scm_id=1007.23409.271287.0&scm-url=1007.23409.271287.0&pvid=e606d278-37c9-4f52-b5e7-4229e9564797&_t=gps-id:pcStoreNewArrivals,scm-url:1007.23409.271287.0,pvid:e606d278-37c9-4f52-b5e7-4229e9564797,tpp_buckets:668%232846%238108%231977&pdp_npi=4%40dis%21EUR%2157.64%2128.82%21%21%2160.40%21%21%40210384b916992918484531700e6b24%2112000035998075049%21rec%21SK%21120116945%21&spm=a2g0o.store_pc_home.smartNewArrivals_2006393372356.1005006151445980](url)

I have choosen ESP32 Wrover Kit as board. Is this correct please ?
Can you tell me the coorect board ? Do I need some special Windows USB driver for uploading of compiled code ?
Thanks for help.
Jozef
![Error-download](https://github.com/ScitiveX/Smart_touch_switch__weather_station__watch_using_wt32-sc01-plus_esp32s3/assets/27333438/9bd73e5b-c1af-4b6b-b281-b008587d5302)

**Comment by ScitiveX** [comment]
Select ESP32S3
Try with arduino IDE 1.8.16
